# Generated by Django 4.2 on 2024-10-19 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0003_alter_advertisement_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="advertisement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="advertisements.advertisement",
                verbose_name="Объявление",
            ),
        ),
    ]
