# Generated by Django 4.2 on 2024-10-23 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0005_alter_review_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="advertisement",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="advertisements.advertisement",
                verbose_name="Объявление",
            ),
            preserve_default=False,
        ),
    ]
