# Generated by Django 4.2 on 2024-10-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0006_alter_review_advertisement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(
                default=1, help_text="Введите текст отзыва", verbose_name="Текст отзыва"
            ),
            preserve_default=False,
        ),
    ]
